version = 0.1
[default.deploy.parameters]
stack_name = "UVA-App-Integrations"
resolve_s3 = true
s3_prefix = "UVA-App-Integrations"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DynamoDBTableName=\"UVA-uqr6xntysfa3lbguhirvcj3pa4-develop\" DynamoDBStreamArn=\"arn:aws:dynamodb:us-east-1:913045965320:table/UVA-uqr6xntysfa3lbguhirvcj3pa4-develop/stream/2024-09-29T16:18:49.463\""
image_repositories = []
