name: SAM devploy on Test

on:
  pull_request:
    branches:
      - main  # Se ejecuta cuando se haga un pull request hacia 'test'
    types:
      - closed  # Asegura que se ejecute solo cuando el PR se haya cerrado (es decir, el merge se haya completado)


jobs:
  validate_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Install pyenv and Python 3.9
        run: |
          curl https://pyenv.run | bash
          export PATH="$HOME/.pyenv/bin:$PATH"
          export PATH="$HOME/.pyenv/shims:$PATH"  # Añadir los shims al PATH
          eval "$(pyenv init --path)"  # Inicializa pyenv en el path
          eval "$(pyenv init -)"  # Inicializa pyenv para el shell
          pyenv install 3.9.20  # Instalar Python 3.9.20
          pyenv global 3.9.20  # Establecer Python 3.9.20 como global
          python --version  # Verificar que Python 3.9 esté correctamente instalado

      - name: Install aws-sam-cli
        run: |
          python -m pip install --upgrade pip  # Asegura que pip está actualizado
          pip install aws-sam-cli  # Instalar aws-sam-cli

      - name: Run Deploy Script
        working-directory: SAM-UVA-App-Integrations
        run: |
          # Asegurarse de que pyenv y Python 3.9 están configurados correctamente
          export PATH="$HOME/.pyenv/shims:$PATH"  # Asegura que los shims están en el PATH
          chmod +x deploy.sh  # Asegura que el script es ejecutable
          ./deploy.sh
