name: SAM Validate and Build on Develop

on:
  push:
    branches:
      - develop  # Se ejecuta solo en la rama 'develop'

jobs:
  validate_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y awscli

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Install pyenv and Python 3.9
        run: |
          curl https://pyenv.run | bash
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          pyenv install 3.9.10
          pyenv global 3.9.10
          python --version  # Verificar que Python 3.9 esté correctamente instalado


      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Validate SAM Template
        working-directory: SAM-UVA-App-Integrations
        run: |
          sam validate --template-file template.yaml  # Corregido para .yaml

      - name: Build SAM Application
        working-directory: SAM-UVA-App-Integrations
        run: |
          sam build --template-file template.yaml  # Corregido para .yaml
