name: SAM Validate and Build on Develop

on:
  push:
    branches:
      - develop  # Se ejecuta solo en la rama 'develop'

jobs:
  validate_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y awscli

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Validate SAM Template
        working-directory: SAM-UVA-App-Integrations
        run: |
          sam validate --template-file template.yml

      - name: Build SAM Application
        working-directory: SAM-UVA-App-Integrations
        run: |
          sam build --template-file template.yml
